# ASP.NET Core - Basic buid Pipeline
# Reference:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - development
  - master
  - dev-pipeline

variables:
  
- ${{ if eq(variables['build.SourceBranchName'], 'master') }}:
  - group: 'PROD-Configuration'
- ${{ if contains(variables['build.SourceBranchName'], 'dev') }}:
  - group: 'DEV-Configuration'
    
pool:
  vmImage: 'ubuntu-latest'

stages: 
  
- stage: Build

  jobs:
  - job: buildJob
    displayName: Build .NET Core App
    variables:
      configuration: 'release'

    steps:
    - task: DotNetCoreCLI@2
      displayName: Restore packages dependencies
      inputs:
        command: restore
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: Build back-end
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '--configuration $(configuration)'

    - task: DotNetCoreCLI@2
      displayName: Publish app to staging
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(configuration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: True

    - task: CopyFiles@2
      displayName: Copy deploy scripts to staging
      inputs:
        sourceFolder: deploy
        targetFolder: $(Build.ArtifactStagingDirectory)/deploy

    - publish: $(Build.ArtifactStagingDirectory)
      displayName: Publish artifact
      artifact: drop

- stage: Deploy

  jobs:
  - deployment: deployJob
    displayName: Provision and deploy to Azure AppService
    environment: $(targetEnv)
    strategy:
      runOnce:
        deploy:

          steps:
          - download: current
            artifact: drop
            
          - task: AzureCLI@2
            displayName: Provisioning WebApp Service
            inputs:
              azureSubscription: $(Azure.Subscription)
              scriptType: pscore
              scriptLocation: scriptPath
              scriptPath: '$(Pipeline.Workspace)/drop/deploy/webapp.ps1'
            env:
              CONN_STRING: $(defaultConnectionString)
            
          - task: AzureWebApp@1
            displayName: Deploy Azure WebApp
            inputs:
              azureSubscription: $(Azure.Subscription)
              appName: $(webApp)
              appType: webAppLinux
              runtimeStack: DOTNETCORE|3.1
              appSettings: '-TZ America/Mexico_City'
              #startUpCommand: 'sh ./startup.sh'
              package: $(Pipeline.Workspace)/drop/*.zip
